---
- name: Deploy FirewallD
  hosts: target1

  tasks:
  - name: Intall firewall service on target server
    # sudo yum install -y firewalld
    become: true
    ansible.builtin.yum:
      name: firewalld
      state: latest

  - name: Start firewall service  
    # sudo service firewalld start
    # sudo systemctl enable firewalld
    become: true
    ansible.builtin.service:
      name: firewalld
      state: started  # start service
      enabled: yes    # enable service after reboot

  - name: Populate firewalld service facts
    # service firewalld status
    ansible.builtin.service_facts:

- name: Configure FirewallD rules for database
  hosts: target1

  tasks:
  - name: Configure firewall rules for database
    # sudo firewall-cmd --permanent --zone=public --add-port=3306/tcp
    become: true
    ansible.posix.firewalld:
      port: 3306/tcp
      permanent: yes
      state: enabled
      zone: public

  - name: Reload firewalld service
    # sudo firewall-cmd --list-all
    # sudo firewall-cmd --reload
    # sudo firewall-cmd --list-all
    become: true
    ansible.builtin.service:
      name: firewalld
      state: restarted

  - name: Populate firewalld service facts
    # service firewalld status
    ansible.builtin.service_facts:

- name: Configure FirewallD rules for web server
  hosts: target1

  tasks:
  - name: Configure firewall rules for web server
    # sudo firewall-cmd --list-all
    # sudo firewall-cmd --permanent --zone=public --add-port=80/tcp
    become: true
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      zone: public
        
  - name: Reload firewalld service
    # sudo firewall-cmd --list-all
    # sudo firewall-cmd --reload
    # sudo firewall-cmd --list-all
    become: true
    ansible.builtin.service:
      name: firewalld
      state: restarted

  - name: Populate firewalld service facts
    # service firewalld status
    ansible.builtin.service_facts:
