---
- name: Deploy database server
  hosts: target1

  pre_tasks:
    - name: Installing python-3 mysql libraries
      become: true
      yum: name=MySQL-python.x86_64 state=present

  tasks:
    - name: Install MariaDB
      # sudo yum install -y mariadb-server
      # edit config if required: sudo vi /etc/my.cnf
      become: true
      ansible.builtin.yum:
        name: mariadb-server
        state: latest

    - name: Start mariadb service
      # sudo service mariadb start
      # sudo systemctl enable mariadb
      become: true
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes

    - name: Populate mariadb service facts
      # service mariadb status
      ansible.builtin.service_facts:
