---
- name: deploy database server
  hosts: target1

  tasks:
    - name: install MariaDB
      # sudo yum install -y mariadb-server
      # edit config if required: sudo vi /etc/my.cnf
      become: true
      yum:
        name: mariadb-server
        state: latest

    - name: start mariadb service
      # sudo service mariadb start
      # sudo systemctl enable mariadb
      become: true
      service:
        namee: mariadb
        state: started
        enabled: yes

    - name: populate mariadb service facts
      # service mariadb status
      ansible.builtin.service_facts:


