---
- name: Deploy web server
  hosts: target1
  vars:
    packages:
      - name: httpd
        required: true
      - name: php
        required: true
      - name: php-mysql
        required: true
      - name: git
        required: true

  tasks:
    - name: Install web server packages
      # sudo yum install -y httpd php php-mysql
      become: true
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: latest
      when: item.required == true
      loop: "{{ packages }}"

    - name: Start httpd service
      # sudo service httpd start
      # sudo systemctl enable httpd
      become: true
      ansible.builtin.service:
        #name: '{{ packages[0] }}'
        name: httpd
        state: started
        enabled: yes

    - name: configure httpd to use index.php
      # sudo sed -i 's/index.html/index.php/g' /etc/httpd/conf/httpd.conf
      become: true
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^(.*)DirectoryIndex(.*)$'
        line: 'DirectoryIndex index.php'
        backrefs: yes

    - name: Restart service httpd
      # sudo service httpd restart
      become: true
      ansible.builtin.service:
        name: httpd
        state: restarted
